### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by ethers** [ConsenSys/gnosis-contracts#13]
For the record, tests are too monolithic (there's only 2 test files currently) and it's easy to miss cases since it's not clear what has been covered, and there are usually test scenarios which do not fit along a linear path.

#4 is an example of a missing scenario.  Another example are boundary cases, such as:

- tokenPrice == stopPrice
- tokenPrice == stopPrice - 1
- tokenPrice == stopPrice + 1

**Comment by Georgi87** [comment]
>tokenPrice == stopPrice - 1 == tokenPrice > stopPrice 
Is covered by every bid sent before the auction is closing.

>tokenPrice == stopPrice + 1 == tokenPrice < stropPrice
Covered by your test case scenario and `test_dutch_auction_stop_price`

>tokenPrice == stopPrice
Is still missing.

**Comment by Georgi87** [comment]
Added test for `tokenPrice == stopPrice` in d21f941d99db2e3084d562a00b45fad5c04bdde9

**Comment by ethers** [comment]
I don't think this should be closed.  Closing this doesn't mean that all or most of the known tests have been written.  For example there are missing tests for `claimTokens` before `tokenLaunched` returns true.  Related #19
