### ISSUE TITLE
Document the pinger

### ISSUE THREAD

**Issue by ethers** [ConsenSys/gnosis-contracts#15]
I think point that needs to be added to spec is details about the "pinger".  I think a pinger is needed to check if the tokenprice has fallen below the stopprice.  So details about how often it runs and what function it invokes.

**Comment by ethers** [comment]
It's not really a pinger since people will probably be invoking the auction contract.  But it might still be helpful in the spec to mention an explicit transaction is needed to end the auction.

**Comment by Georgi87** [comment]
Hm, I think it is obvious that a transaction is needed to alter the contract state. The frontend is showing the actual state calling `updateStage`:

```
   function updateStage()
        public
        timedTransitions
        returns (Stages)
    {
        return stage;
    }
```
