### ISSUE TITLE
Tests for GnosisToken.sol

### ISSUE THREAD

**Issue by ethers** [ConsenSys/gnosis-contracts#21]
For example a test matrix would have 2 rows:
`transfer` and `transferFrom`

There would then be 2 columns:
`!dutchAuction.tokenLaunched() returns true`
`!dutchAuction.tokenLaunched() returns false`

And 2 more columns for:
`msg.sender != address(dutchAuction) returns true`
`msg.sender != address(dutchAuction) returns false`

related #19 and #13

**Comment by Georgi87** [comment]
Checking those cases I think they are actually covered:

`dutchAuction.tokenLaunched() == false` + `msg.sender != address(dutchAuction) == true`
Bidder tries to transfer shares before waiting period is over. Tested in:
https://github.com/ConsenSys/gnosis-contracts/blob/security_audit/contracts/tests/do/test_dutch_auction.py#L93

`dutchAuction.tokenLaunched() == false` + `msg.sender != address(dutchAuction) == false`
Waiting period is going and someone is claiming tokens. Tested in:
https://github.com/ConsenSys/gnosis-contracts/blob/security_audit/contracts/tests/do/test_dutch_auction.py#L76

`dutchAuction.tokenLaunched() == true` + `msg.sender != address(dutchAuction) == true`
Waiting period is over and someone transfers tokens. Tested in:
https://github.com/ConsenSys/gnosis-contracts/blob/security_audit/contracts/tests/do/test_dutch_auction.py#L100

`dutchAuction.tokenLaunched() == true` + `msg.sender != address(dutchAuction) == false`
Waiting period is over and someone is claiming tokens. Not tested. Adding now.

**Comment by Georgi87** [comment]
Added case for: `dutchAuction.tokenLaunched() == true + msg.sender != address(dutchAuction) == false`
https://github.com/ConsenSys/gnosis-contracts/blob/security_audit/contracts/tests/do/test_dutch_auction.py#L96
