### ISSUE TITLE
Reference to exact multisigwallet code

### ISSUE THREAD

**Issue by ethers** [ConsenSys/gnosis-contracts#22]
fwiw the wallet is missing this commit
https://github.com/ConsenSys/MultiSigWallet/commit/004da438880fbdc23ab345dca7d086b0e01abb6d

Also, can the readme mention that the wallet files come from this:
https://github.com/ConsenSys/MultiSigWallet/tree/004da438880fbdc23ab345dca7d086b0e01abb6d/contracts/solidity

**Comment by Georgi87** [comment]
thanks! :)
