### ISSUE TITLE
Bypass the daily limit

### ISSUE THREAD

**Issue by Georgi87** [ConsenSys/gnosis-contracts#24]
This bug was found as part of the Gnosis bug bounty.

Call:
submitTransaction(yourAdress,dailylimit,0,0)
It gives you the daily limit.
Then call
submitTransaction(bullshitAddress,2^256-dailylimit,0,0)
The transaction won't be executed because the call will fail, however, spentToday will be reset to 0.

**Comment by Georgi87** [comment]
Fixed in c7417fe7379a27f93de6be4cc994a40ab820a992

**Comment by ethers** [comment]
Rest of the discussion on this issue will be at https://github.com/ConsenSys/MultiSigWallet/issues/35
