### ISSUE TITLE
msg.sender should get the change back in bid()

### ISSUE THREAD

**Issue by ethers** [ConsenSys/gnosis-contracts#27]
Found by Gonçalo Sá @GNSPS
https://github.com/ConsenSys/gnosis-contracts/commit/30dca8f14c13419086910a372e5c245bbd83c023#commitcomment-21689161

**Comment by Georgi87** [comment]
This is not a bug but needs some explaination:

We added the receiver address to allow direct participation via Shapeshift. A user will be able to send BTC to Shapeshift and Shapeshift converts it to ETH and sends it directly to the auction contract on behalf of the user. In the edge case that the full amount is not invested, the remaining ETH will be send to the user.

Sending the remaining ETH back to the receiver address is the desired behaviour in this case.

**Comment by GNSPS** [comment]
Had not seen this pattern to interact with Shapeshift before so it just struck me as an error. Good to know! 😄

**Comment by ethers** [comment]
It would still be ideal to have a comment in the code; in the future maybe a link to an explanation if a paragraph is too much in the code.

**Comment by Georgi87** [comment]
I agree. I added a comment: https://github.com/ConsenSys/gnosis-contracts/commit/16088244e101ad0eb0f25d496bfc8c36d2dd76bc
