### ISSUE TITLE
calcMaxWithdraw should be constant

### ISSUE THREAD

**Issue by ethers** [ConsenSys/gnosis-contracts#28]
Found by Gonçalo Sá @GNSPS
https://github.com/ConsenSys/gnosis-contracts/commit/81e91cd06f4c36b0ed4226415e7b6eb627e35091#commitcomment-21689227

**Comment by Georgi87** [comment]
I agree, this should be changed. However, currently it doesn't make any difference.

From solidity docs:
```
The constant keyword for functions is currently not enforced by the compiler. Furthermore, it is not enforced by the EVM, so a contract function that “claims” to be constant might still cause changes to the state.
```

**Comment by GNSPS** [comment]
Completely agree, as I put it in the audit:

> Given the function doesn't change the contract's state, for the **sake of readability**, it should be marked as `constant`.

**Comment by ethers** [comment]
Yes, currently it doesn't make any difference and this is a minor, but these contracts strive to be as good a model as can be, so improvements to the code that are objective should be pointed out.  (Also a short commit if other commits are needed for other reasons.)

**Comment by Georgi87** [comment]
It was added and I agree there is no reason to not add it :) I just forgot to add it in the first place.

**Comment by Georgi87** [comment]
Added: https://github.com/ConsenSys/gnosis-contracts/commit/4dd7b158f7b07b72bbfc625770aff01215519be3#diff-de2a0ecf49f1010c177f7e582f9f5913R83
