### ISSUE TITLE
MultiSigWallet needs to be updated with canonical

### ISSUE THREAD

**Issue by ethers** [ConsenSys/gnosis-contracts#3]
MultiSigWallet.sol needs to be updated when the canonical https://github.com/ConsenSys/MultiSigWallet is reviewed

**Comment by Georgi87** [comment]
Agreed, we are currently discussing if we want to use the DailyLimit or the basic version and will update this soon.

**Comment by Georgi87** [comment]
Updated it: 248fc0c3abb4a87d59b02fa5c9acda43440b8009

The code is pretty much frozen. I don't expect many changes.

**Comment by ethers** [comment]
technically we should reopen this...  the wallet is now going to come from the dapp branch?  and the dailylimit one needs to also be copied to this repo

**Comment by Georgi87** [comment]
I have updated the master branch and the gnosis-contracts repo has the latest wallet contracts.

**Comment by ethers** [comment]
Maybe reopen this while https://github.com/ConsenSys/MultiSigWallet/issues/57 is pending?
