### ISSUE TITLE
vestingPeriod of zero

### ISSUE THREAD

**Issue by ethers** [ConsenSys/gnosis-contracts#30]
https://github.com/ConsenSys/gnosis-contracts/commit/a7b9494990baa961da68e7a10075ed90795cdd19
can now allow zero, which can cause a division by zero (in calcMaxWithdraw).

Perhaps in the constructor throw if zero.  And should also add test for zero.  And ideally, tests for other vestingPeriods that are "interesting" and could cause issues, such as -1 (which would become "max uint", and would lead to a division by "max uint")

**Comment by Georgi87** [comment]
Fixed in https://github.com/ConsenSys/gnosis-contracts/commit/ea1b2bd00587c8ce32e49b765e2b161bc5041e35
