### ISSUE TITLE
`withdrawnTokens` can be tampered with

### ISSUE THREAD

**Issue by GNSPS** [ConsenSys/gnosis-contracts#31]
https://github.com/ConsenSys/gnosis-contracts/commit/4dd7b158f7b07b72bbfc625770aff01215519be3#diff-de2a0ecf49f1010c177f7e582f9f5913

Allows for a new `token` argument in every public function of _Vesting.sol_. This, allied to the fact that there is no overflow check when incrementing `withdrawnTokens` (v. [L65](https://github.com/ConsenSys/gnosis-contracts/blob/4dd7b158f7b07b72bbfc625770aff01215519be3/contracts/solidity/DO/Vesting.sol#L65)), now allows for a malicious _owner_ to completely empty the contract by repeatedly overflowing the state var by calling the withdraw function with a ERC20 contract he controls as argument.

**Recommendation**

Maybe now it would be better if `withdrawnTokens`  is made to be a mapping?

```
mapping (address => uint) public withdrawnTokens;
```

and then use/update it accordingly in every function:

```
withdrawnTokens[token] += _value;
```

**Comment by Georgi87** [comment]
Good catch. Thanks @GNSPS. I will undo the change and make the token address fixed at setup time.

**Comment by Georgi87** [comment]
Issue is solved in https://github.com/ConsenSys/gnosis-contracts/commit/ae6ae428a60e29b49ff97222d05f45cfdf1fa5f4
