### ISSUE TITLE
bid during/after a finalizeAuction

### ISSUE THREAD

**Issue by ethers** [ConsenSys/gnosis-contracts#4]
~https://github.com/ConsenSys/gnosis/issues/45~

**Comment by ethers** [comment]
There's a bid, the timedTransitions runs and calls finalizeAuction.  Then the bid code runs.
This scenario isn't clear.  Is there a test/s for this?  It seems the person making the bid will not get their tokens, since the tokens have already been transferred to the Gnosis wallet?
It's also a code smell that the contract state is being updated via
```
        bids[msg.sender] += investment;
        totalRaised += investment;
```
when the auction was already finalized...

**Comment by Georgi87** [comment]
When finalizeAuction is executed stage is set to `stage = Stages.AuctionEnded;`. After the  `timedTransitions` modifier the `atStage(Stages.AuctionStarted)` is called and will throw because stage is now in `Stages.AuctionEnded`.

**Comment by Georgi87** [comment]
There is a test for this: https://github.com/ConsenSys/gnosis-contracts/blob/master/contracts/tests/dao/test_dao_dutch_auction.py#L79

**Comment by ethers** [comment]
Thanks for explaining, I see that the order of modifiers is critical.  Later, I think we may need to consider whether it is a good tip that modifiers shouldn't change state (maybe they should only enforce preconditions), like how most code is using them.

The mentioned test is:
```
        # Bidder 3 places a bid
        bidder_3 = 2
        value_3 = 500000 * 10 ** 18  # 1M Ether
        self.s.block.set_balance(accounts[bidder_3], value_3 * 2)
        self.dao_auction.bid(sender=keys[bidder_3], value=value_3)  <---- need test when this fails immediately?
        # Auction is over, no more bids are accepted
        self.s.block.set_balance(accounts[bidder_3], value_3 * 2)
        self.assertRaises(TransactionFailed, self.dao_auction.bid, sender=keys[bidder_3], value=value_3)
```

But I don't think the test is for the edge case that you described, otherwise the very first `self.dao_auction.bid(sender=keys[bidder_3], value=value_3)` should already `throw`.
The current test is for a bid after a finalizeAuction.
Seems to be a missing test for a bid which invokes finalizeAuction: a test where finalizeAuction is _during_ a bid.
