### ISSUE TITLE
Compiler version for MistWallet

### ISSUE THREAD

**Issue by ethers** [ConsenSys/gnosis-contracts#8]
Should MistWallet.sol be compiled using the same compiler version that the Ethereum Foundation used?  Or we want to use 0.4.4?  Or something else, like 0.3.x that was used for SingularDTV?

**Comment by ethers** [comment]
Or shall we remove MistWallet from the repo?
Otherwise need to document how the code matches with this part of the spec:
```
The ETH storing multisig contract will use the same bytecode as the wallet used by the Ethereum Foundation: https://etherscan.io/address/0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae#code
```

**Comment by Georgi87** [comment]
I removed the mist wallet from the repo 248fc0c3abb4a87d59b02fa5c9acda43440b8009

We will only use the new multisig wallet.
